"""initial clean schema

Revision ID: 60314f2da823
Revises: 
Create Date: 2025-08-25 15:18:57.195568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60314f2da823'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('binders', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_binders_set_id', 'sets', ['set_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('binders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_binders_set_id', type_='foreignkey')

    # ### end Alembic commands ###
