"""messed with BinderCard model

Revision ID: 726db1c32ac1
Revises: 239ff36f295e
Create Date: 2025-08-24 17:12:17.139198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726db1c32ac1'
down_revision = '239ff36f295e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('binder_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owned', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('binder_cards', schema=None) as batch_op:
        batch_op.drop_column('owned')

    # ### end Alembic commands ###
