"""add set metadata to binders

Revision ID: b52d6e5b0aa4
Revises: 6d2c4cdfbc94
Create Date: 2025-08-24 18:31:23.963243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52d6e5b0aa4'
down_revision = '6d2c4cdfbc94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('binders', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_binders_set_id', 'sets', ['set_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('binders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_binders_set_id', type_='foreignkey')

    # ### end Alembic commands ###
